[logger]
level = "error"
messageFormat = "%(asctime)s %(message)s"

[runner]
magicEnabled = false
installTracer = false

[server]
maxUploadSize = 200
runOnSave = false

[client]
showErrorDetails = false

[theme]
base = "dark"
primaryColor = "#4CAF50"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"